
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: darkgolly
  password: 22316

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: darkgolly
  password: 22316


production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
